### ISSUE TITLE
`.spec.vars` is not working properly

### ISSUE THREAD

**Issue by tomhuang12** [weaveworks/tf-controller#80] opened 2022-02-03 04:58 UTC
Tried setting `vars` to the followings:

```
  vars:
  - name: region
    value: us-east-1
```
and 
```
vars:
  - name: cluster_spec
    value:
      region: us-east-1
      env: dev
      node_count: 10
      public: false
```

Both resulted the following error:
```
E0203 04:57:12.795883       7 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.Terraform: failed to list *v1alpha1.Terraform: json: cannot unmarshal object into Go struct field Variable.items.spec.vars.value of type string
```

**Comment by phoban01** [comment] 2022-02-03 14:15
Thanks for catching @tomhuang12. This issue was caused by the wrong container image being specified. 

I've pushed a fix in #82.

**Closed by phoban01** 2022-02-03 14:15 UTC
