### ISSUE TITLE
I keep getting "segmentation violation" on the tf-controller

### ISSUE THREAD

**Issue by magnusboman** [weaveworks/tf-controller#227] opened 2022-05-17 19:31 UTC
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x148e069]

goroutine 415 [running]:
github.com/fluxcd/pkg/runtime/events.(*Recorder).AnnotatedEventf(0x0, {0x1bef760, 0xc000bc8600}, 0xc000604180, {0x1995f5e, 0x7}, {0x19a1f9c, 0x2}, {0xc000234b00, 0x295}, ...)
	/go/pkg/mod/github.com/fluxcd/pkg/runtime@v0.13.2/events/recorder.go:124 +0x69
github.com/weaveworks/tf-controller/controllers.(*TerraformReconciler).fireEvent(_, {_, _}, {{{0x163a1d9, 0x9}, {0xc00088d300, 0x20}}, {{0xc0000f0736, 0x9}, {0x0, ...}, ...}, ...}, ...)
	/workspace/controllers/terraform_controller.go:1436 +0x258
github.com/weaveworks/tf-controller/controllers.(*TerraformReconciler).Reconcile(0xc0001000f0, {0x1c06628, 0xc0007f7c80}, {{{0xc0000f0740, 0x18ca8a0}, {0xc0000f0736, 0x30}}})
	/workspace/controllers/terraform_controller.go:281 +0x1875
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc000788000, {0x1c06628, 0xc0007f7bf0}, {{{0xc0000f0740, 0x18ca8a0}, {0xc0000f0736, 0x413c54}}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:114 +0x26f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000788000, {0x1c06580, 0xc000919380}, {0x17ea780, 0xc000228420})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:311 +0x33e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000788000, {0x1c06580, 0xc000919380})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:223 +0x357
```

**Comment by chanwit** [comment] 2022-05-18 11:20
Thank you @magnusboman!
It seems to be a known issue.
Duplicate of #212

**Closed** 2022-05-19 07:37 UTC
