### ISSUE TITLE
Use of AWS role_arn doesn't work

### ISSUE THREAD

**Issue by magnusboman** [weaveworks/tf-controller#228] opened 2022-05-17 19:35 UTC
I'm trying to make use of the AWS role_arn as follows:

```provider "aws" {
  access_key = var.access_key
  secret_key = var.secret_key
  region     = var.region

  assume_role {
    role_arn = var.role_arn
  }

  default_tags {
    tags = {
      Environment = "Development"
      Owner       = "Me"
      Application = "BestAppEver"
    }
  }
}
```

This works locally, but when the tf-controller tries to use it, I get the following error:

```{"level":"error","ts":"2022-05-17T19:22:23.411Z","logger":"controller.terraform","msg":"Reconciliation failed after 14.47423464s, next try in 1m0s","reconciler group":"infra.contrib.fluxcd.io","reconciler kind":"Terraform","name":"x-account","namespace":"flux-system","revision":"master/99ad9c90f8e9680d9e92dcd9774c3f97da9375b0","error":"error running Plan: rpc error: code = Unknown desc = exit status 1\n\nError: error configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found.\n\nPlease see https://registry.terraform.io/providers/hashicorp/aws\nfor more information about providing credentials.\n\nError: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, request send failed, Get \"http://169.254.169.254/latest/meta-data/iam/security-credentials/\": dial tcp 169.254.169.254:80: i/o timeout\n\n\n  with provider[\"registry.terraform.io/hashicorp/aws\"],\n  on main.tf line 18, in provider \"aws\":\n  18: provider \"aws\" {\n\n"}```

I'm running this in a local k3s cluser.

**Comment by chanwit** [comment] 2022-05-18 11:24
The error said you need an AWS block to configure credentials.
It was working locally may be because you have AWS credentials file in your HOME, so Terraform just picked it up.

**Comment by chanwit** [comment] 2022-05-18 11:25
Noted for documentations.
It would be great to have a Getting Started guide for AWS.

**Comment by magnusboman** [comment] 2022-05-18 18:11
@chanwit I tried it after removing my .aws directory and it works fine with terraform:
```
$ echo $AWS_ACCESS_KEY_ID

$ ls -l ~/.aws
ls: cannot access '/home/magnus.boman/.aws': No such file or directory
```

I see that the first line was cut of in my initial paste of the terraform script, it should be like this:
```
provider "aws" {
  access_key = var.access_key
  secret_key = var.secret_key
  region     = var.region

  assume_role {
    role_arn = var.role_arn
  }

  default_tags {
    tags = {
      Environment = "Development"
      Owner       = "Me"
      Application = "BestAppEver"
    }
  }
}
```

**Comment by chanwit** [comment] 2022-05-19 06:44
That looks correct to me now. Thank you @magnusboman 
I'll test a setup with `role_arn` to see what's the root cause of this problem.

**Comment by madAndroid** [comment] 2023-11-03 12:39
Hi @magnusboman - just to follow up on this issue - were you able to get to the bottom of why the credentials were not being picked up? You mention running this locally with k3d - are you making the AWS environment variables available to the runner pods in your `Terraform` resource? it would be good if you can give an example of the `Terraform` CR that you're using, so that we can examine it and try determine why this is not working for you.

**Comment by yitsushi** [comment] 2024-01-05 04:02
2 months without activity, I close this issue for now, @magnusboman if you still need assistance with this, feel free to re-open the issue.

**Closed by yitsushi** 2024-01-05 04:02 UTC
Labels: kind/bug
