### ISSUE TITLE
Unknown desc = error pending plan and plan's name in  the secret are not matched

### ISSUE THREAD

**Issue by mcortinas** [weaveworks/tf-controller#599] opened 2023-05-15 13:50 UTC
Hello,

 Last week I was starting several Terraform manifest inside GKE and I started received these messages `Unknown desc = error pending plan and plan's name in the secret are not matched: `

 This error has appeared in several Terraform, as you can see here:
![Screenshot_20230515_154306](https://github.com/weaveworks/tf-controller/assets/692263/7ac5835c-a9c4-4567-ba5f-737cb41ebb3b)

 Let me share more info just from 1 Terraform manifest, maybe i don't see what is the root of this issue:

- terraform 
[terraform.tar.gz](https://github.com/weaveworks/tf-controller/files/11478434/terraform.tar.gz)

- cm from plan 
[cm.tar.gz](https://github.com/weaveworks/tf-controller/files/11478439/cm.tar.gz)

- secret from plan 
[secret.tar.gz](https://github.com/weaveworks/tf-controller/files/11478436/secret.tar.gz)

Let me also describe my environment:
- kubernetes in Google, GKE:  Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.10-gke.2300"
- FluxCD v0.41.2
- Terraform Controller v0.14.0

Could you help me fixing this? 
Marc

**Comment by mcortinas** [comment] 2023-05-15 19:54
Let me add I was change the source of all these Terraform object changing the tag referenced from 0.0.1 to 1.1.0 (I just wanted to use the same tag in all my objects, initially was a cosmetic change) but the artifact content (terraform code) and also the plan obtained was the same

**Comment by mcortinas** [comment] 2023-05-26 17:46
After fix my issue with tf-runner image, I checked and this has not been fixed or maybe I'm wrong with some configuration. Let me reming my environment, basically fluxcd running version v2.0.0-rc.1 and tf-controller v0.15.0-rc.1 as you suggested

**Comment by mcortinas** [comment] 2023-05-29 09:19
I'm using tf-controller reading and writing tfstate from a Google bucket , GCS. I detected if there are some change in Terraform code should be applied but the terraform plan is the same, it means no change in cloud vendor in the target i can see this message, TFplan computed in go code from tf-controller is different than the previous applied.  I'm not sure if using tfstate from GCS affect in some way this tfplan computed is different due to I'm using `BackendConfig` and `backendConfigsFrom` in Terraform .spec . 

This is interesting, if i'm removing the tfstate this error dissapear.

**Comment by greenu** [comment] 2023-06-01 13:16
v0.14.2 fixed that for me

**Comment by mcortinas** [comment] 2023-06-06 22:41
I also upgraded to  v2.0.0-rc.5 and tf-controller v0.15.0-rc.5 and it's not fixed for me. I also checked with break-glass and there are no changes in Terraform plan. I guess the new TFPlan computed should change some metadata and it's different in the name of plan-$TAG@sha256:HASH from the previous one....

**Comment by marccortinas** [comment] 2023-06-29 20:41
This issues it's happening several times and this don't help me to convince my colleagues to migrate Terraform jobs to this . My environment is uptodate (v2.0.0-rc.5 and tf-controller v0.15.0-rc.5 ). Let me share more files if this can help me.
[tfplan-fluxcd-cloudflare-account-liligo.tar.gz](https://github.com/weaveworks/tf-controller/files/11909910/tfplan-fluxcd-cloudflare-account-liligo.tar.gz)
[tf-controller-log-issued.tar.gz](https://github.com/weaveworks/tf-controller/files/11909911/tf-controller-log-issued.tar.gz)
[account-liligo.terraform.tar.gz](https://github.com/weaveworks/tf-controller/files/11909912/account-liligo.terraform.tar.gz)
[tfplan-fluxcd-cloudflare-account-liligo.secret.tar.gz](https://github.com/weaveworks/tf-controller/files/11910345/tfplan-fluxcd-cloudflare-account-liligo.secret.tar.gz)
I checked the secret data value in the secret tfplan-fluxcd-cloudflare-account-liligo.secret.tar.gz  is compressed two times, maybe this could be the root cause, could be???? 

If I launch `echo "XXXX" | base64 -d | gunzip -c | gunzip -c` i can see this output: 
```@
datadogapikey/
"string" 833b14efec6df996d51b9408a27fe964=

account-id/
"string" 9b10dca6d786432ba56af7c0f75c109aM
cloudflareapitoken7
"string"(ctC6AZav6yQutj5TvFpAtPHArh1ESoi5v5hFOGCS2
datadog-ddsource
"string"cloudflare-audit/
datadog-ddtags
tring"liligo_commit_8B7provider["registry.terraform.io/cloudflare/cloudflare"]J
account_id 9b10dca6d786432ba56af7c0f75c109adatasetaudit_logsdestination_confٔdatadog://http-intake.logs.datadoghq.eu/v1/input?header_DD-API-KEY=833b14efec6df996d51b9408a27fe964&ddsource=cloudflare-audit&ddtags=liligo_commit_8enabledæfilterfrequencyhighid256125kindlogpull_optionskfields=ActorID,ActorIP,ID,OwnerID,NewValue,OldValue,OwnerID,ResourceID,ResourceType,When&timestamps=rfc3339nameaudit-logownership_challengezone_id

destination_conf"

destination_confRnullj cloudflare_logpush_job.audit_jobj
gcs
access_tokenbucketedo-tfstate-lab-servicescredentialsencryption_keyimpersonate_service_account%impersonate_service_account_delegateskms_encryption_keyprefix.tf-workspaces/fluxcd-cloudflare/account/liligostorage_custom_endpointfluxcd-cloudflarer1.5.02023-06-29T19:52:13Zgzip: stdin has more than one entry--rest ignored
```

**Comment by chanwit** [comment] 2023-06-30 05:36
This issue relates plan ids.

**Comment by mcortinas** [comment] 2023-07-07 10:56
This bug is still on-going, let me try to re-open this issue

**Comment by chanwit** [comment] 2023-07-07 11:01
We would try to fix this by slightly changing the semantics of `force: true` to skip the annotation validation.

**Comment by chanwit** [comment] 2023-07-10 10:52
It seems we can close this as discussed.

**Closed by chanwit** 2023-07-10 10:52 UTC
Labels: terraform, team/wild-watermelon
