### ISSUE TITLE
The branch-planner does not clean up after running

### ISSUE THREAD

**Issue by madAndroid** [weaveworks/tf-controller#923] opened 2023-09-06 06:58 UTC
**User story**
As a WeGO user who’s working with Terraform resources, I would like the Terraform CRs I create to be cleaned up, so that I don’t have to manually remove orphaned resources. 

**Acceptance Criteria**
- [ ] The Controller can delete every TF resource generated by the branch planner, and there are no orphaned resources.
- [ ] When the user isn’t happy with a PR and closes it, the branch planner clears up all affected objects. 
- [ ] When no resources are referring to the Git repo object that points at the PR branch then and only then does it delete the Git repo source.

**Notes About Implementation**
- Establish a 1:1 relationship between source and object. This is based on an assumption that it’s already 1:1 but not working/set up that way.
- Test and guarantee this 1:1 property. 
- Write test case to generate the multiple objects and source and check the number to guarantee it’s working. If you create five objects you have to have five sources as well. 

*****
When we have the branch planner installed and enabled, the additional `Terraform` CRs for branches are created, but never cleaned up, leaving orphaned resources that need to be manually removed:

```
kc get terraforms.infra.contrib.fluxcd.io -A
NAMESPACE     NAME                                                                                 READY     STATUS                                                                                                AGE
flux-system   example-wge-workshops-dynamodb-table                                                 True      No drift: v4.38.0-v1alpha11@sha256:6033f3b9fb6458dda7f432ea5ce1a8dbb9560c2388d612f0d1036ba03cf2e063   5d17h
flux-system   irsa-role-as-demo-dev-01-external-dns                                                Unknown   Terraform Planning                                                                                    4d19h
flux-system   irsa-role-as-demo-dev-01-external-dns-delete-clusters-branch-7i71ib-33               False     error running Plan: rpc error: code = Internal desc = exit status 1...                                116m
flux-system   irsa-role-as-demo-dev-01-external-dns-delete-clusters-branch-cuy98h-31               False     Source 'GitRepository/flux-system/flux-system-delete-clusters-branch-cuy98h-31' not found             118m
flux-system   irsa-role-as-demo-dev-01-external-dns-delete-clusters-branch-h066yf-37               False     Source 'GitRepository/flux-system/flux-system-delete-clusters-branch-h066yf-37' not found             21m
flux-system   irsa-role-as-demo-dev-01-external-dns-delete-clusters-branch-h3h05j-29               False     Source 'GitRepository/flux-system/flux-system-delete-clusters-branch-h3h05j-29' not found             16h
flux-system   irsa-role-as-demo-dev-01-external-dns-gitopssets-pullrequests-19                     False     Source 'GitRepository/flux-system/flux-system-gitopssets-pullrequests-19' not found                   35h
flux-system   irsa-role-as-demo-dev-01-external-dns-wge-create-branch-1ltgan-36                    False     Source 'GitRepository/flux-system/flux-system-wge-create-branch-1ltgan-36' not found                  46m
flux-system   irsa-role-as-demo-dev-01-external-dns-wge-create-branch-2d0th-25                     False     Source 'GitRepository/flux-system/flux-system-wge-create-branch-2d0th-25' not found                   19h
flux-system   irsa-role-as-demo-dev-01-external-dns-wge-create-branch-4ft00a-18                    False     Source 'GitRepository/flux-system/flux-system-wge-create-branch-4ft00a-18' not found                  39h
flux-system   irsa-role-as-demo-dev-01-external-dns-wge-create-branch-78sved-26                    False     Source 'GitRepository/flux-system/flux-system-wge-create-branch-78sved-26' not found                  17h
flux-system   irsa-role-as-demo-dev-01-external-dns-wge-create-branch-91djwn-38                    False     Source 'GitRepository/flux-system/flux-system-wge-create-branch-91djwn-38' not found                  14m
flux-system   irsa-role-as-demo-dev-01-external-dns-wge-create-branch-bm0vu8-20                    False     Source 'GitRepository/flux-system/flux-system-wge-create-branch-bm0vu8-20' not found                  23h
flux-system   irsa-role-as-demo-dev-01-external-dns-wge-create-branch-cp0rpj-23                    False     Source 'GitRepository/flux-system/flux-system-wge-create-branch-cp0rpj-23' not found                  19h
flux-system   irsa-role-as-demo-dev-01-external-dns-wge-create-branch-epjgcg-28                    False     Source 'GitRepository/flux-system/flux-system-wge-create-branch-epjgcg-28' not found                  17h
flux-system   irsa-role-as-demo-dev-01-external-dns-wge-create-branch-m38e4t-17                    False     Source 'GitRepository/flux-system/flux-system-wge-create-branch-m38e4t-17' not found                  39h
flux-system   irsa-role-as-demo-dev-01-external-dns-wge-create-branch-nfe4lf-14                    False     Source 'GitRepository/flux-system/flux-system-wge-create-branch-nfe4lf-14' not found                  41h
flux-system   irsa-role-as-demo-dev-01-external-dns-wge-create-branch-nnuxlf-22                    False     Source 'GitRepository/flux-system/flux-system-wge-create-branch-nnuxlf-22' not found                  19h
flux-system   irsa-role-as-demo-dev-01-external-dns-wge-create-branch-qy94gf-35                    False     Source 'GitRepository/flux-system/flux-system-wge-create-branch-qy94gf-35' not found                  51m
flux-system   irsa-role-as-demo-dev-01-external-dns-wge-create-branch-wkbgx-27                     False     Source 'GitRepository/flux-system/flux-system-wge-create-branch-wkbgx-27' not found                   17h
flux-system   secret-store-irsa-as-demo-dev-01-external-secrets-delete-clusters-branch-cuy98h-31   False     Source 'GitRepository/flux-system/flux-system-delete-clusters-branch-cuy98h-31' not found             118m
flux-system   secret-store-irsa-as-demo-dev-01-external-secrets-delete-clusters-branch-h066yf-37   False     Source 'GitRepository/flux-system/flux-system-delete-clusters-branch-h066yf-37' not found             21m
flux-system   secret-store-irsa-as-demo-dev-01-external-secrets-delete-clusters-branch-h3h05j-29   False     Source 'GitRepository/flux-system/flux-system-delete-clusters-branch-h3h05j-29' not found             16h
flux-system   secret-store-irsa-as-demo-dev-01-external-secrets-gitopssets-pullrequests-19         False     Source 'GitRepository/flux-system/flux-system-gitopssets-pullrequests-19' not found                   35h
flux-system   secret-store-irsa-as-demo-dev-01-external-secrets-wge-create-branch-1ltgan-36        False     Source 'GitRepository/flux-system/flux-system-wge-create-branch-1ltgan-36' not found                  46m
flux-system   secret-store-irsa-as-demo-dev-01-external-secrets-wge-create-branch-2d0th-25         False     Source 'GitRepository/flux-system/flux-system-wge-create-branch-2d0th-25' not found                   19h
flux-system   secret-store-irsa-as-demo-dev-01-external-secrets-wge-create-branch-4ft00a-18        False     Source 'GitRepository/flux-system/flux-system-wge-create-branch-4ft00a-18' not found                  39h
flux-system   secret-store-irsa-as-demo-dev-01-external-secrets-wge-create-branch-78sved-26        False     Source 'GitRepository/flux-system/flux-system-wge-create-branch-78sved-26' not found                  17h
flux-system   secret-store-irsa-as-demo-dev-01-external-secrets-wge-create-branch-91djwn-38        False     Source 'GitRepository/flux-system/flux-system-wge-create-branch-91djwn-38' not found                  14m
flux-system   secret-store-irsa-as-demo-dev-01-external-secrets-wge-create-branch-bm0vu8-20        False     Source 'GitRepository/flux-system/flux-system-wge-create-branch-bm0vu8-20' not found                  23h
flux-system   secret-store-irsa-as-demo-dev-01-external-secrets-wge-create-branch-cp0rpj-23        False     Source 'GitRepository/flux-system/flux-system-wge-create-branch-cp0rpj-23' not found                  19h
flux-system   secret-store-irsa-as-demo-dev-01-external-secrets-wge-create-branch-epjgcg-28        False     Source 'GitRepository/flux-system/flux-system-wge-create-branch-epjgcg-28' not found                  17h
flux-system   secret-store-irsa-as-demo-dev-01-external-secrets-wge-create-branch-m38e4t-17        False     Source 'GitRepository/flux-system/flux-system-wge-create-branch-m38e4t-17' not found                  39h
flux-system   secret-store-irsa-as-demo-dev-01-external-secrets-wge-create-branch-nnuxlf-22        False     Source 'GitRepository/flux-system/flux-system-wge-create-branch-nnuxlf-22' not found                  19h
flux-system   secret-store-irsa-as-demo-dev-01-external-secrets-wge-create-branch-qy94gf-35        False     Source 'GitRepository/flux-system/flux-system-wge-create-branch-qy94gf-35' not found                  51m
flux-system   secret-store-irsa-as-demo-dev-01-external-secrets-wge-create-branch-wkbgx-27         False     Source 'GitRepository/flux-system/flux-system-wge-create-branch-wkbgx-27' not found                   17h
```

**Comment by chanwit** [comment] 2023-09-06 07:11
related to https://github.com/weaveworks/tf-controller/issues/898

**Comment by darrylweaver** [comment] 2023-10-02 09:45
I tested this with the latest version 0.16.0-rc.3 and this will only clear up correctly for 1 terraform resource being planned by the  branch planner.  If you have more than 1 resource then the closing of the PR results in:

1 - delete the first terraform resource - completes correctly.
2 - deletes the git repository source referring to the PR branch
3 - Now all other TF resources are stuck as now there is no valid git repo object, blocking deletion of any other TF resources.

Workaround is to remove the finalizer and delete manually.

Workflow we would need:

1 - delete each terraform resource that was generated by the branch planner.
2 - When no resources are referring to the git repo object pointing at the PR branch, then and only then, delete the Git repo source.

**Comment by yitsushi** [comment] 2023-10-06 12:22
>  If you have more than 1 resource then the closing of the PR results in

Why does a branch has more then one PR? Or did I misunderstood that?

**Comment by LappleApple** [comment] 2023-11-08 16:32
Next step is to test it again with the recent version, then can conclude it.

**Comment by thefirstofthe300** [comment] 2023-11-15 22:30
I don't think the latest release is going to fix this issue. The server iterates through all of the planner objects [here](https://github.com/weaveworks/tf-controller/blob/main/internal/server/polling/server.go#L246) and deletes both the plan object and source object at the same time for each object. If those plan objects share a source object, the first plan object will be successfully deleted still, but subsequent attempts to delete the Terraform objects will bail [here](https://github.com/weaveworks/tf-controller/blob/main/internal/server/polling/terraform.go#L210) due to the 404 returned by the k8s API.

**Comment by yitsushi** [comment] 2023-11-15 23:03
> If those plan objects share a source object

When can this happen? Right now (as far as I know) the branch planner creates a clone from the source for each and every branch planner Terraform object. That was (kind of) my question back in Oct, how can two separate PR Terraform object refer to the same Source object, or how can a single PR have more than one planner Terraform resources, or basically any combinations like that.

The planner uses a very simple flow:
1. Find the source TF resource
2. Find its Source
3. Clone Source (change some values like branch)
4. Clone TF resource (change some values, like source ref, only plan, etc)
5. When the PR is closed, delete the Source and the TF Resource.

@chanwit (iirc) had a patch around a month ago to reverse the deletion order of the Source and TF resources so the Terraform resource is deleted first.

**Comment by thefirstofthe300** [comment] 2023-11-16 05:18
The case I ran into was having multiple Terraform resources which referred to the same source but had different paths. In that case,all of the Terraform resources referencing the original source are duplicated while only one instance of the source is created.

My company currently uses a TF mono repo for our multiple environments so we need the ability for multiple Terraform resources to reference a single source and be cleaned up properly.

**Comment by yitsushi** [comment] 2023-11-16 08:26
I think that's an issue with the planner creature, it should clone all resources always, no matter how many TF references you have to the same Source, if you have 5 PRs across all TF resources, you should have 5 separate clone of the Source object, same or different doesn't matter. Can you please verify the issue is there in recent version too?

**Comment by thefirstofthe300** [comment] 2023-11-16 15:46
I'm seeing that the root path is special cased in the reconciliation code so I should add that due to a migration my team is still working on, we have both the root of the repo and subdirectories in the repo configured as Terraform resources.

**Comment by thefirstofthe300** [comment] 2023-11-16 15:58
Looking through the code, it looks like the source for a Terraform resources related to a PR is named only based on the original source name and the PR id: https://github.com/weaveworks/tf-controller/blob/main/internal/server/polling/terraform.go#L145

If multiple Terraform resources are cloned for planning for a single PR, the name of the source object would always be the same for each Terraform resource. The controller may attempt to reconcile the source multiple times, but would only create it once due to the name collision.

**Comment by yitsushi** [comment] 2023-11-16 16:33
I went through all possible cases I can think of and finally I understand the use-case and the issue. 

Use-case:
1. There are 4 Terraform resources (t1, t2, t3, t4)
2. There is one Source resource (s1)
3. `t1` uses `s1` with path to `/team-a`.
4. `t2` uses `s1` with path to `/team-b`.
5. `t3` uses `s1` with path to `/team-c`.
6. `t4` uses `s1` with path to `/team-d`.

If we create a PR that changes `/team-a` and `/team-b` at the same time, the system will try to create `t1-clone` and `t2-clone` with `s1-clone` and `s1-clone`. As it's the same PR, the name of the two generate source IDs will be the same therefore they will share that resource.

If `EnablePathScope` is `false` (default as I remember), the system will try to create all four (`t1-clone`, `t2-clone`, `t3-clone`, `t4-clone`).

@thefirstofthe300: Am I on the right track with this?

---

Solution:
1. On user side: turn on `EnablePathScope` to reduce the issue and create smaller, scoped PRs. That's useful in general as you don't want to create new resources for a branch where you have no changes. (it still doesn't resolve the issue if a PR contains changes in different scopes)
2. Add original terraform name (or hash of it) to the name of the generate source to avoid conflicts. I think it's much easier and cheaper than always checking if there are resources, add an incremental number, and add extra labels to track which on is the original.

@chanwit: Any idea, notes, or concerns?

**Comment by thefirstofthe300** [comment] 2023-11-16 18:43
@yitsushi You're on the right track. One special aspect of our environment is that we not only utilize paying for Terraform resources but we also use the root of the repo for a Terraform resource.

In other words, given three resources tf1, TF2, and tf3, tf1 has a path of ./, tf2 a path of ./tf2 and tf3 a path of ./tf3.

I know, it's a terrible layout that I wouldn't recommend to anyone, but it's what I inherited.

**Comment by yitsushi** [comment] 2023-11-16 23:28
Thanks for the clarification, now I understand the issue and the use case better.

**Closed** 2023-11-21 15:55 UTC
Labels: area/terraform, team/wild-watermelon, priority/high, area/branch-planner
