### ISSUE TITLE
The tfstate Secrets are not deleted after Terraform object deletion

### ISSUE THREAD

**Issue by Sergey-Kizimov** [weaveworks/tf-controller#1171] opened 2023-12-28 00:34 UTC
When a Terraform object is deleted, the `tfstate-*` Secrets and Leases are not deleted.

The expected behavior is to delete the state secrets and corresponding leases

Possible resolution:
Add OwnerReference to `tfstate` Secrets and Leases 

Not sure if this bug is in `tf-controller` or in Terraform kubernetes backend.

**Comment by yitsushi** [comment] 2024-01-05 03:41
As far as I know, right now the expected behaviour is to not delete them. We have a [investigation tracker issue](https://github.com/weaveworks/tf-controller/issues/937) to re-evaluate all create Secrets if we want to delete them or not.

The reason why we keep it, that way a deleted resource can be recovered. I'm not entirely sure, but I remember something like this. I think @chanwit knows more about it.

**Comment by yitsushi** [comment] 2024-01-05 03:46
I found the original one: https://github.com/weaveworks/tf-controller/issues/456

That issue has [some explanation](https://github.com/weaveworks/tf-controller/issues/456#issuecomment-1316321286). It's old and it was not never really revisited.

I tend to the logic to delete everything unless the user told us not to do (they created a secret and we just update, there is a field on the Terraform resource like `keepState: true`). The mentioned feature didn't land in the codebase, it doesn't really have any actionable specs and I don't it will be implemented in the near (2-4 months) future if it will be ever.

**Comment by yitsushi** [comment] 2024-01-05 03:46
Closing this as dupe, reopen if you think it's not.

**Closed by yitsushi** 2024-01-05 03:46 UTC

**Comment by yitsushi** [comment] 2024-01-05 03:53
Meanwhile, found the mentioned feature from Dec 22, 2021: https://github.com/weaveworks/tf-controller/issues/2
